[workspace]
resolver = "2"
members = [
    "src/catalog",
    "src/conductor",
    "src/score",
    "src/sql",
    "src/ensemble-x",
    "src/ostinator",
    "src/workspace-hack"
]

[workspace.package]
edition = "2021"
